import { NextResponse } from 'next/server';
import dbConnect from '@/lib/mongodb';
import Course from '@/models/Course';

const seedData = [
  {
    title: 'Advanced Full-Stack Engineering',
    description: 'Master modern architectures, distributed systems, and enterprise-grade deployment strategies using bleeding-edge frameworks.',
    duration: '9 Months',
    category: 'Development',
    imageUrl: '/assets/2026c1c758e55619434709adf691f57f.png',
    altText: 'Professional software engineer working on high-end monitors with clean minimalist code in a modern office setup',
    tags: ['React', 'Node.js', 'PostgreSQL', 'Docker', 'TypeScript', 'AWS', 'GraphQL'],
    tuition: '$12,500',
    originalTuition: '$15,000',
    nextStartDate: 'September 15, 2026',
    location: 'Online / Hybrid',
    credential: 'Professional Certification',
    modules: [
      { number: '01', title: 'Frontend Foundations & UI/UX', description: 'Deep dive into semantic HTML5, CSS Grid/Flexbox, and responsive design principles.' },
      { number: '02', title: 'JavaScript Deep Dive & ES6+', description: 'Asynchronous programming, closures, prototypes, and the modern JavaScript engine.' },
      { number: '03', title: 'React Ecosystem & State Management', description: 'Component architecture, hooks, context API, and advanced state management.' },
      { number: '04', title: 'Backend Architecture & APIs', description: 'Node.js, Express.js, RESTful & GraphQL API Design, Authentication with JWT and OAuth2.' },
    ],
    instructor: { name: 'Dr. Marcus Chen', role: 'Senior Software Architect, ex-Google & Microsoft', imageUrl: '/assets/06a4b78655b1455e35a2c6c763c68ca7.png', bio: 'Dr. Chen has over 15 years of experience in distributed systems and cloud infrastructure. He has published numerous papers on web performance and has mentored over 500 developers.' },
  },
  {
    title: 'Machine Learning & AI Ethics',
    description: 'Dive deep into predictive modeling, neural networks, and the critical ethical frameworks of automated systems.',
    duration: '12 Months',
    category: 'Data Science',
    imageUrl: '/assets/940e06dfe14e8611b57bf89a101b66d6.png',
    altText: 'Abstract data visualization on a large screen with glowing blue and teal nodes representing neural networks',
    tags: ['Python', 'PyTorch', 'TensorFlow', 'Scikit-learn', 'NLP', 'Computer Vision'],
    tuition: '$14,000',
    originalTuition: '$17,000',
    nextStartDate: 'October 1, 2026',
    location: 'Online',
    credential: 'Graduate Certificate',
    modules: [
      { number: '01', title: 'Python for Data Science', description: 'NumPy, Pandas, and Matplotlib for advanced data manipulation.' },
      { number: '02', title: 'Supervised & Unsupervised Learning', description: 'Regression, classification, clustering, and dimensionality reduction.' },
      { number: '03', title: 'Deep Learning with PyTorch', description: 'Neural networks, CNNs, RNNs, and Transformer architectures.' },
      { number: '04', title: 'AI Ethics & Responsible Deployment', description: 'Bias mitigation, fairness frameworks, and explainable AI.' },
    ],
    instructor: { name: 'Prof. Elena Rodriguez', role: 'Head of Computer Science', imageUrl: '/assets/783a1f025ba759a75e3c9c5944f7b3b9.png', bio: 'A pioneer in distributed systems and cloud architecture, Prof. Rodriguez oversees the graduate CS curricula.' },
  },
  {
    title: 'Network Defense & Cryptography',
    description: 'Protect global infrastructure through advanced penetration testing, threat hunting, and modern encryption protocols.',
    duration: '6 Months',
    category: 'Cybersecurity',
    imageUrl: '/assets/6d145504b16d2284f5092f5b84e31a4a.png',
    altText: 'Close-up of a high-tech server room with glowing green security lights and intricate cabling representing digital safety',
    tags: ['Kali Linux', 'Wireshark', 'Metasploit', 'Cryptography', 'SIEM', 'OSCP'],
    tuition: '$9,500',
    originalTuition: '$12,000',
    nextStartDate: 'November 1, 2026',
    location: 'Online / Hybrid',
    credential: 'Professional Certification',
    modules: [
      { number: '01', title: 'Network Fundamentals & Protocols', description: 'TCP/IP, DNS, HTTP, TLS/SSL deep dive.' },
      { number: '02', title: 'Ethical Hacking & Penetration Testing', description: 'Reconnaissance, exploitation, and post-exploitation techniques.' },
      { number: '03', title: 'Cryptography & PKI', description: 'Symmetric/asymmetric encryption, hashing, digital signatures.' },
      { number: '04', title: 'Threat Intelligence & Incident Response', description: 'SIEM tools, threat hunting, and forensics.' },
    ],
    instructor: { name: 'Dr. Julian Vance', role: 'Head of Cybersecurity', imageUrl: '/assets/242e4703ebae0f66c553dfb3c21b6084.png', bio: 'Former lead security architect for global tech firms, Dr. Vance brings real-world threat intelligence to the academic sphere.' },
  },
  {
    title: 'Cloud Native Architecture',
    description: 'Learn to build and scale applications on AWS, Azure, and Google Cloud with Kubernetes and Serverless computing.',
    duration: '8 Months',
    category: 'Cloud',
    imageUrl: '/assets/68bd5fcdb30df959c7fbd697a0326b61.png',
    altText: 'Conceptual digital cloud landscape with interconnected nodes and glowing particles against a deep dark background',
    tags: ['AWS', 'Azure', 'GCP', 'Kubernetes', 'Docker', 'Terraform', 'Serverless'],
    tuition: '$11,000',
    originalTuition: '$13,500',
    nextStartDate: 'September 20, 2026',
    location: 'Online',
    credential: 'Professional Certification',
    modules: [
      { number: '01', title: 'Cloud Fundamentals & IaaS', description: 'VMs, networking, storage on AWS, Azure, and GCP.' },
      { number: '02', title: 'Containerization with Docker', description: 'Building, running, and orchestrating containerized apps.' },
      { number: '03', title: 'Kubernetes Orchestration', description: 'Pods, deployments, services, ingress, and Helm charts.' },
      { number: '04', title: 'Infrastructure as Code', description: 'Terraform, CloudFormation, and GitOps workflows.' },
    ],
    instructor: { name: 'Dr. Marcus Thorne', role: 'Dean of ITI Global', imageUrl: '/assets/681b2067a4a17bf9d6f5dd4cebd11c0f.png', bio: 'With over 25 years in computational theory and a PhD from Stanford, Dr. Thorne leads the institute with a focus on ethical AI and global connectivity.' },
  },
  {
    title: 'Mobile App Innovation',
    description: 'Create high-performance cross-platform mobile experiences focusing on UI/UX excellence and native performance.',
    duration: '6 Months',
    category: 'Development',
    imageUrl: '/assets/546b2efeacb5acf15394f63a5b815495.png',
    altText: 'Modern laptop screen showing clean Python code with high contrast syntax highlighting on a minimalist desk',
    tags: ['React Native', 'Flutter', 'iOS', 'Android', 'Firebase', 'Expo'],
    tuition: '$9,000',
    originalTuition: '$11,000',
    nextStartDate: 'October 15, 2026',
    location: 'Online',
    credential: 'Professional Certification',
    modules: [
      { number: '01', title: 'Mobile UI Fundamentals', description: 'Platform design guidelines, accessibility, and responsive layouts.' },
      { number: '02', title: 'React Native Deep Dive', description: 'Components, navigation, state management, and native modules.' },
      { number: '03', title: 'Flutter & Dart', description: 'Cross-platform development with Google Flutter.' },
      { number: '04', title: 'App Deployment & Store Publishing', description: 'CI/CD for mobile, App Store, and Play Store guidelines.' },
    ],
    instructor: { name: 'Prof. Elena Rodriguez', role: 'Head of Computer Science', imageUrl: '/assets/783a1f025ba759a75e3c9c5944f7b3b9.png', bio: 'A pioneer in distributed systems and cloud architecture, Prof. Rodriguez oversees the graduate CS curricula.' },
  },
  {
    title: 'Enterprise Risk Management',
    description: 'Strategize and implement large-scale security policies to protect organizational assets from evolving global threats.',
    duration: '10 Months',
    category: 'Cybersecurity',
    imageUrl: '/assets/11650e2af719f42aded6ae5c21073389.png',
    altText: 'Clean minimal digital security dashboard on a monitor with biometric authentication graphics and dark mode UI',
    tags: ['ISO 27001', 'NIST', 'Risk Assessment', 'GRC', 'Compliance', 'Audit'],
    tuition: '$13,000',
    originalTuition: '$16,000',
    nextStartDate: 'November 15, 2026',
    location: 'Online / Hybrid',
    credential: 'Graduate Certificate',
    modules: [
      { number: '01', title: 'Risk Management Frameworks', description: 'NIST, ISO 27001, and COBIT frameworks deep dive.' },
      { number: '02', title: 'GRC Tools & Compliance', description: 'Governance, risk, and compliance platforms.' },
      { number: '03', title: 'Business Continuity Planning', description: 'Disaster recovery, BCP, and incident response plans.' },
      { number: '04', title: 'Security Auditing & Reporting', description: 'Audit processes, evidence collection, and executive reporting.' },
    ],
    instructor: { name: 'Dr. Julian Vance', role: 'Head of Cybersecurity', imageUrl: '/assets/242e4703ebae0f66c553dfb3c21b6084.png', bio: 'Former lead security architect for global tech firms, Dr. Vance brings real-world threat intelligence to the academic sphere.' },
  },
];

export async function GET() {
  await dbConnect();
  await Course.deleteMany({});
  await Course.insertMany(seedData);
  return NextResponse.json({ message: `Seeded ${seedData.length} courses successfully!` });
}
